"""baseline schema

Revision ID: 1d68b1e53cac
Revises: 
Create Date: 2026-06-28 10:19:32.094026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d68b1e53cac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('target', sa.String(length=256), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_actor'), 'audit_log', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_log_ts'), 'audit_log', ['ts'], unique=False)
    op.create_table('batches',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_images', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('image_list', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batches_created_at'), 'batches', ['created_at'], unique=False)
    op.create_index(op.f('ix_batches_created_by'), 'batches', ['created_by'], unique=False)
    op.create_table('kv_settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('licenses',
    sa.Column('scan_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('scan_id')
    )
    op.create_table('scans',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('image_name', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scan_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('critical', sa.Integer(), nullable=False),
    sa.Column('high', sa.Integer(), nullable=False),
    sa.Column('medium', sa.Integer(), nullable=False),
    sa.Column('low', sa.Integer(), nullable=False),
    sa.Column('negligible', sa.Integer(), nullable=False),
    sa.Column('unknown', sa.Integer(), nullable=False),
    sa.Column('total_packages', sa.Integer(), nullable=False),
    sa.Column('total_secrets', sa.Integer(), nullable=False),
    sa.Column('report_url', sa.Text(), nullable=True),
    sa.Column('sbom_report_url', sa.Text(), nullable=True),
    sa.Column('image_digest', sa.String(length=256), nullable=True),
    sa.Column('scan_quality', sa.String(length=32), nullable=True),
    sa.Column('batch_id', sa.String(length=64), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_batch_id'), 'scans', ['batch_id'], unique=False)
    op.create_index(op.f('ix_scans_created_by'), 'scans', ['created_by'], unique=False)
    op.create_index(op.f('ix_scans_image_name'), 'scans', ['image_name'], unique=False)
    op.create_index(op.f('ix_scans_scan_timestamp'), 'scans', ['scan_timestamp'], unique=False)
    op.create_index(op.f('ix_scans_status'), 'scans', ['status'], unique=False)
    op.create_table('vulnerabilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.String(length=64), nullable=False),
    sa.Column('cve_id', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('package_name', sa.String(length=512), nullable=True),
    sa.Column('package_version', sa.String(length=256), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('epss_score', sa.Float(), nullable=True),
    sa.Column('in_kev', sa.Boolean(), nullable=False),
    sa.Column('fix_available', sa.Boolean(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulnerabilities_cve_id'), 'vulnerabilities', ['cve_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_scan_id'), 'vulnerabilities', ['scan_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_severity'), 'vulnerabilities', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vulnerabilities_severity'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_scan_id'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_cve_id'), table_name='vulnerabilities')
    op.drop_table('vulnerabilities')
    op.drop_index(op.f('ix_scans_status'), table_name='scans')
    op.drop_index(op.f('ix_scans_scan_timestamp'), table_name='scans')
    op.drop_index(op.f('ix_scans_image_name'), table_name='scans')
    op.drop_index(op.f('ix_scans_created_by'), table_name='scans')
    op.drop_index(op.f('ix_scans_batch_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_table('licenses')
    op.drop_table('kv_settings')
    op.drop_index(op.f('ix_batches_created_by'), table_name='batches')
    op.drop_index(op.f('ix_batches_created_at'), table_name='batches')
    op.drop_table('batches')
    op.drop_index(op.f('ix_audit_log_ts'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
