"""add batches.detail

Revision ID: 3263093159e3
Revises: 1d68b1e53cac
Create Date: 2026-06-28 14:26:48.234597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3263093159e3'
down_revision: Union[str, None] = '1d68b1e53cac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add with a server_default so the existing batch rows get '{}' and the
    # NOT NULL constraint holds; then drop the default (the app supplies detail
    # on every write, matching the other JSONB columns).
    op.add_column('batches', sa.Column(
        'detail', postgresql.JSONB(astext_type=sa.Text()),
        nullable=False, server_default=sa.text("'{}'::jsonb"),
    ))
    op.alter_column('batches', 'detail', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batches', 'detail')
    # ### end Alembic commands ###
